/**
 * Every user-facing literal on the public site lives here.
 * German only by design — the site has no i18n layer (plan: public-site
 * migration, Task C1). Add literals as pages get ported; never inline them.
 */
export const strings = {
  site: {
    name: "HB Dragons e.V.",
    logoAlt: "HB Dragons Logo",
    claim: {
      courtPart: "One Court, ",
      culturesPart: "United Cultures",
    },
  },
  nav: {
    home: "Home",
    news: "News",
    teams: "Teams",
    uberUns: "Über Uns",
    team: "Team",
    story: "Story",
    philosophie: "Philosophie",
    projekte: "Projekte",
    spielplan: "Spielplan",
    probetraining: "Probetraining",
    shop: "Shop",
    supporter: "Supporter",
    downloads: "Downloads",
    dragons: "Dragons",
    impressum: "Impressum",
    datenschutz: "Datenschutz",
    openMenu: "Menü öffnen",
    closeMenu: "Menü schließen",
  },
  footer: {
    clubName: "Hanover Basketball Dragons e.V.",
    email: "info@hbdragons.de",
    contactHeading: "Kontaktiere uns",
    datenschutzerklaerung: "Datenschutzerklärung",
    impressum: "Impressum",
    followHeading: "Folge uns",
    instagram: "Instagram",
    facebook: "Facebook",
    youtube: "YouTube",
    linkedin: "LinkedIn",
  },
  home: {
    title: "HB Dragons e.V. — Startseite",
    scrollHint: "Scroll",
    newsHeading: "Aktuelle News",
    allNews: "Alle News",
    joinTitle: "Werde Teil unserer Familie",
    joinCta: "Probetraining vereinbaren",
    socialWallHeading: "Social Wall",
    statsMembers: "MITGLIEDER",
    statsTeams: "TEAMS",
    statsYears: "JAHRE DABEI",
  },
  nextGames: {
    heading: "Unsere nächsten Spiele",
    empty: "Keine Spiele geplant",
    allGames: "Alle Spiele",
    versus: "VS",
  },
  notFound: {
    title: "Seite nicht gefunden — HB Dragons e.V.",
    code: "404",
    heading: "Seite nicht gefunden",
    message: "Diese Seite gibt es nicht (mehr) — vielleicht ein Tippfehler im Link, oder die Seite ist umgezogen.",
    backHome: "Zur Startseite",
  },
  spielplan: {
    pageTitle: "Spielplan — HB Dragons e.V.",
    heading: "Spielplan",
    filterAll: "Alle Spiele",
    filterHome: "Heimspiele",
    filterAway: "Auswärtsspiele",
    teamsFilter: "Teams",
    selectAll: "Alle auswählen",
    deselectAll: "Alle abwählen",
    exportLabel: "Excel Export",
    gamesCount: "Spiele",
    loadError: "Der Spielplan konnte nicht geladen werden. Bitte versuche es später erneut.",
    noGame: "Kein Spiel gefunden",
    mapAriaLabel: "Karte",
  },
  teams: {
    pageTitle: "Teams — HB Dragons e.V.",
    heading: "Teams",
    titleSuffix: " — HB Dragons e.V.",
    goToTeam: "Zum Team",
    overlayTeam: "Team",
    coach: "Coach",
    trainerFallback: "Trainer",
    lastGame: "Letztes Spiel",
    nextGame: "Nächstes Spiel",
    tabGames: "Spielplan",
    tabStandings: "Tabelle",
    colDate: "Datum",
    colTime: "Uhrzeit",
    colHome: "Heim",
    colResult: "Ergebnis",
    colGuest: "Gast",
    colVenue: "Halle",
    colRank: "Rang",
    colName: "Name",
    colGames: "Spiele",
    colWins: "S",
    colLosses: "N",
    colPoints: "Punkte",
    colBaskets: "Körbe",
    teamsCount: "Teams",
    standingsError: "Fehler beim Laden",
  },
} as const;
