packages:
  - apps/*
  - packages/*
allowBuilds:
  basketball-bund-sdk: true
  esbuild: true
  '@swc/core': true
  '@parcel/watcher': true
  core-js: false
  msgpackr-extract: false
  sharp: false
  unrs-resolver: false
