import { Hono } from "hono";
import { healthRoutes } from "./health.routes";
import { syncRoutes } from "./admin/sync.routes";
import { matchRoutes } from "./admin/match.routes";
import { teamRoutes } from "./admin/team.routes";
import { settingsRoutes } from "./admin/settings.routes";
import { leagueRoutes } from "./admin/league.routes";
import { venueRoutes } from "./admin/venue.routes";
import { refereeRoutes } from "./admin/referee.routes";
import { refereeRulesRoutes } from "./admin/referee-rules.routes";
import { standingsRoutes } from "./admin/standings.routes";
import { boardRoutes } from "./admin/board.routes";
import { taskRoutes } from "./admin/task.routes";
import { bookingRoutes } from "./admin/booking.routes";
import { notificationRoutes } from "./admin/notification.routes";
import { notificationTestRoutes } from "./admin/notification-test.routes";
import { eventRoutes } from "./admin/event.routes";
import { watchRuleRoutes } from "./admin/watch-rule.routes";
import { channelConfigRoutes } from "./admin/channel-config.routes";
import { userRoutes } from "./admin/user.routes";
import { socialRoutes } from "./admin/social.routes";
import { deviceRoutes } from "./device.routes";
import { publicMatchRoutes } from "./public/match.routes";
import { publicStandingsRoutes } from "./public/standings.routes";
import { publicTeamRoutes } from "./public/team.routes";
import { publicHomeRoutes } from "./public/home.routes";
import { publicAssetsRoutes } from "./public/assets.routes";
import { refereeGamesRoutes } from "./referee/games.routes";
import { refereeAssignmentRoutes } from "./referee/assignment.routes";
import { adminRefereeAssignmentRoutes } from "./admin/referee-assignment.routes";
import { adminRefereeHistoryRoutes } from "./admin/referee-history.routes";

const routes = new Hono();

routes.route("/", healthRoutes);
routes.route("/admin", syncRoutes);
routes.route("/admin", matchRoutes);
routes.route("/admin", teamRoutes);
routes.route("/admin", settingsRoutes);
routes.route("/admin", leagueRoutes);
routes.route("/admin", venueRoutes);
routes.route("/admin", refereeRoutes);
routes.route("/admin", refereeRulesRoutes);
routes.route("/admin", standingsRoutes);
routes.route("/admin", boardRoutes);
routes.route("/admin", taskRoutes);
routes.route("/admin", bookingRoutes);
routes.route("/admin", notificationRoutes);
routes.route("/admin", notificationTestRoutes);
routes.route("/admin", eventRoutes);
routes.route("/admin", watchRuleRoutes);
routes.route("/admin", channelConfigRoutes);
routes.route("/admin", userRoutes);
routes.route("/admin/social", socialRoutes);
routes.route("/api/devices", deviceRoutes);
routes.route("/public", publicMatchRoutes);
routes.route("/public", publicStandingsRoutes);
routes.route("/public", publicTeamRoutes);
routes.route("/public", publicHomeRoutes);
routes.route("/public", publicAssetsRoutes);
routes.route("/referee", refereeGamesRoutes);
routes.route("/referee", refereeAssignmentRoutes);
routes.route("/admin", adminRefereeAssignmentRoutes);
routes.route("/admin", adminRefereeHistoryRoutes);

export { routes };
