import { defineConfig, globalIgnores } from "eslint/config";
import nextCoreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypeScript from "eslint-config-next/typescript";
import { base } from "../../eslint.config.base.mjs";

export default defineConfig([
  ...base,
  ...nextCoreWebVitals,
  ...nextTypeScript,
  globalIgnores([
    ".next/**",
    "next-env.d.ts",
    // Payload regenerates this on startup (`payload generate:importmap`).
    "src/app/(payload)/admin/importMap.js",
    // Generated by `payload generate:types`.
    "src/payload-types.ts",
  ]),
]);
