import {
  pgTable,
  serial,
  integer,
  varchar,
  boolean,
  date,
  time,
  timestamp,
  index,
} from "drizzle-orm/pg-core";
import { matches } from "./matches";
import { teams } from "./teams";

export const refereeGames = pgTable(
  "referee_games",
  {
    id: serial("id").primaryKey(),
    apiMatchId: integer("api_match_id").notNull().unique(),
    matchId: integer("match_id").references(() => matches.id),
    matchNo: integer("match_no").notNull(),
    kickoffDate: date("kickoff_date").notNull(),
    kickoffTime: time("kickoff_time").notNull(),
    homeTeamName: varchar("home_team_name", { length: 200 }).notNull(),
    guestTeamName: varchar("guest_team_name", { length: 200 }).notNull(),
    leagueName: varchar("league_name", { length: 200 }),
    leagueShort: varchar("league_short", { length: 50 }),
    venueName: varchar("venue_name", { length: 200 }),
    venueCity: varchar("venue_city", { length: 100 }),
    sr1OurClub: boolean("sr1_our_club").notNull(),
    sr2OurClub: boolean("sr2_our_club").notNull(),
    sr1Name: varchar("sr1_name", { length: 150 }),
    sr2Name: varchar("sr2_name", { length: 150 }),
    sr1RefereeApiId: integer("sr1_referee_api_id"),
    sr2RefereeApiId: integer("sr2_referee_api_id"),
    sr1Status: varchar("sr1_status", { length: 20 }).notNull().default("open"),
    sr2Status: varchar("sr2_status", { length: 20 }).notNull().default("open"),
    isCancelled: boolean("is_cancelled").notNull().default(false),
    isForfeited: boolean("is_forfeited").notNull().default(false),
    homeClubId: integer("home_club_id"),
    guestClubId: integer("guest_club_id"),
    isHomeGame: boolean("is_home_game").notNull().default(false),
    isGuestGame: boolean("is_guest_game").notNull().default(false),
    homeTeamId: integer("home_team_id").references(() => teams.id),
    guestTeamId: integer("guest_team_id").references(() => teams.id),
    leagueApiId: integer("league_api_id"),
    ownClubRefs: boolean("own_club_refs").notNull().default(false),
    dataHash: varchar("data_hash", { length: 64 }),
    lastSyncedAt: timestamp("last_synced_at", { withTimezone: true }),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    index("referee_games_match_id_idx").on(table.matchId),
    index("referee_games_kickoff_date_idx").on(table.kickoffDate),
    index("referee_games_home_team_id_idx").on(table.homeTeamId),
    index("referee_games_guest_team_id_idx").on(table.guestTeamId),
  ],
);
