/**
 * AI Act Art. 50(1) (in force since 2026-08-02): before the first interaction
 * the member is told that the answers are generated by an AI (Google Gemini),
 * may be wrong, and that no other person's personal data belongs in the chat —
 * and acknowledges it explicitly. ADR 0005. The native app keeps the same flag
 * under the same key in its own storage.
 */
export const AI_NOTICE_KEY = "assistant_ai_notice_ack";

export type AiNoticeState = "pending" | "show" | "hidden";

/** Pure: the panel renders from this and branches nowhere else. */
export function resolveNoticeState({
  loaded,
  acknowledged,
}: {
  loaded: boolean;
  acknowledged: boolean;
}): AiNoticeState {
  if (!loaded) return "pending";
  return acknowledged ? "hidden" : "show";
}

// localStorage throws in some private windows and when site data is blocked.
// An unreadable flag shows the notice again, which is the safe side.
export function readAiNoticeAcknowledged(): boolean {
  try {
    return window.localStorage.getItem(AI_NOTICE_KEY) === "1";
  } catch {
    return false;
  }
}

export function acknowledgeAiNotice(): void {
  try {
    window.localStorage.setItem(AI_NOTICE_KEY, "1");
  } catch {
    // The in-memory state still hides the notice for this session.
  }
}
