// @vitest-environment happy-dom
import "@testing-library/jest-dom/vitest";
import { describe, it, expect, vi, afterEach } from "vitest";
import { render, screen, cleanup, fireEvent } from "@testing-library/react";
import { NextIntlClientProvider } from "next-intl";

const setMessages = vi.fn();
const clearError = vi.fn();
const chatMock = vi.fn(() => ({
  messages: [] as unknown[],
  sendMessage: vi.fn(),
  status: "ready",
  error: undefined as Error | undefined,
  stop: vi.fn(),
  regenerate: vi.fn(),
  setMessages,
  clearError,
}));
vi.mock("@ai-sdk/react", () => ({ useChat: () => chatMock() }));
vi.mock("ai", () => ({ DefaultChatTransport: class { constructor(_o: unknown) {} } }));

import { AssistantPanel } from "./assistant-panel";

const messages = {
  qa: {
    title: "AI assistant",
    close: "Close",
    error: "Something went wrong. Please try again.",
    empty: "e",
    greetingTitle: "Hi!",
    greetingSubtitle: "sub",
    examplesLabel: "Try asking",
    examples: ["Who plays this weekend?"],
    placeholder: "p",
    send: "Send",
    stop: "Stop",
    newChat: "Start a new chat",
    hint: "Answers are generated by Google Gemini and may contain mistakes.",
    notice: {
      title: "You are chatting with an AI",
      body: "Answers are generated by Google's Gemini model.",
      acknowledge: "Got it",
    },
  },
};

function wrap(ui: React.ReactNode) {
  return (
    <NextIntlClientProvider locale="en" messages={messages}>
      {ui}
    </NextIntlClientProvider>
  );
}

// The AI notice persists its acknowledgement in localStorage (#236).
afterEach(() => window.localStorage.clear());

describe("<AssistantPanel> dialog semantics", () => {
  afterEach(cleanup);

  it("exposes itself as a modal dialog labelled by its own title", () => {
    render(wrap(<AssistantPanel onClose={vi.fn()} />));
    const dialog = screen.getByRole("dialog", { name: "AI assistant" });
    expect(dialog).toHaveAttribute("aria-modal", "true");
  });

  it("moves focus into the dialog on open", () => {
    render(wrap(<AssistantPanel onClose={vi.fn()} />));
    const dialog = screen.getByRole("dialog");
    expect(dialog).toContainElement(document.activeElement as HTMLElement);
  });

  it("closes on Escape", () => {
    const onClose = vi.fn();
    render(wrap(<AssistantPanel onClose={onClose} />));
    fireEvent.keyDown(screen.getByRole("dialog"), { key: "Escape" });
    expect(onClose).toHaveBeenCalledTimes(1);
  });

  it("traps Tab focus inside the dialog, wrapping past the last focusable element", () => {
    render(wrap(<AssistantPanel onClose={vi.fn()} />));
    const dialog = screen.getByRole("dialog");
    const focusable = dialog.querySelectorAll<HTMLElement>(
      'button:not([disabled]), [href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])',
    );
    expect(focusable.length).toBeGreaterThan(1);
    const last = focusable[focusable.length - 1]!;
    const first = focusable[0]!;

    last.focus();
    fireEvent.keyDown(dialog, { key: "Tab" });
    expect(document.activeElement).toBe(first);
  });

  it("traps Shift+Tab focus inside the dialog, wrapping before the first focusable element", () => {
    render(wrap(<AssistantPanel onClose={vi.fn()} />));
    const dialog = screen.getByRole("dialog");
    const focusable = dialog.querySelectorAll<HTMLElement>(
      'button:not([disabled]), [href], input:not([disabled]), select:not([disabled]), textarea:not([disabled]), [tabindex]:not([tabindex="-1"])',
    );
    const last = focusable[focusable.length - 1]!;
    const first = focusable[0]!;

    first.focus();
    fireEvent.keyDown(dialog, { key: "Tab", shiftKey: true });
    expect(document.activeElement).toBe(last);
  });

  it("restores focus to the element that was focused before the dialog opened", () => {
    const trigger = document.createElement("button");
    trigger.textContent = "open";
    document.body.appendChild(trigger);
    trigger.focus();
    expect(document.activeElement).toBe(trigger);

    const { unmount } = render(wrap(<AssistantPanel onClose={vi.fn()} />));
    expect(document.activeElement).not.toBe(trigger);

    unmount();
    expect(document.activeElement).toBe(trigger);
    trigger.remove();
  });
});

// Issue #148: a rejected message stays in `messages`, and DefaultChatTransport
// re-sends the whole list every turn, so a single 400 dead-ended the chat until
// the page was reloaded. `setMessages([])` alone is not enough — AI SDK v6 parks
// `status` at "error" and keeps `error` set, so the banner would survive the
// reset; `clearError()` is what returns the chat to "ready".
describe("<AssistantPanel> recovery from a rejected message", () => {
  afterEach(() => {
    cleanup();
    setMessages.mockClear();
    clearError.mockClear();
    chatMock.mockReturnValue({
      messages: [],
      sendMessage: vi.fn(),
      status: "ready",
      error: undefined,
      stop: vi.fn(),
      regenerate: vi.fn(),
      setMessages,
      clearError,
    });
  });

  function renderInError() {
    chatMock.mockReturnValue({
      messages: [{ id: "m1", role: "user", parts: [{ type: "text", text: "hi" }] }],
      sendMessage: vi.fn(),
      status: "error",
      error: new Error("400"),
      stop: vi.fn(),
      regenerate: vi.fn(),
      setMessages,
      clearError,
    });
    render(wrap(<AssistantPanel onClose={vi.fn()} />));
  }

  it("offers a new-chat control while the chat is in an error state", () => {
    renderInError();
    expect(screen.getByRole("button", { name: "Start a new chat" })).toBeInTheDocument();
  });

  it("clears the transcript and the error state when it is used", () => {
    renderInError();
    fireEvent.click(screen.getByRole("button", { name: "Start a new chat" }));
    expect(setMessages).toHaveBeenCalledWith([]);
    expect(clearError).toHaveBeenCalledTimes(1);
  });

  it("does not offer the control when there is no error to recover from", () => {
    render(wrap(<AssistantPanel onClose={vi.fn()} />));
    expect(screen.queryByRole("button", { name: "Start a new chat" })).not.toBeInTheDocument();
  });
});

// Issue #236 / ADR 0005: the first interaction on a browser starts with the AI
// notice; the composer stays locked until it is acknowledged, and the hint
// under the composer never goes away.
describe("<AssistantPanel> AI notice", () => {
  afterEach(cleanup);

  it("shows the notice instead of the greeting and locks the composer on a fresh browser", () => {
    render(wrap(<AssistantPanel onClose={vi.fn()} />));
    expect(screen.getByText("You are chatting with an AI")).toBeInTheDocument();
    expect(screen.queryByText("Hi!")).not.toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Send" })).toBeDisabled();
  });

  it("swaps the notice for the greeting and unlocks the composer once acknowledged", () => {
    render(wrap(<AssistantPanel onClose={vi.fn()} />));
    fireEvent.click(screen.getByRole("button", { name: "Got it" }));
    expect(screen.getByText("Hi!")).toBeInTheDocument();
    expect(screen.queryByText("You are chatting with an AI")).not.toBeInTheDocument();
    expect(screen.getByRole("button", { name: "Send" })).toBeEnabled();
    expect(window.localStorage.getItem("assistant_ai_notice_ack")).toBe("1");
  });

  it("goes straight to the greeting when the notice was acknowledged earlier", () => {
    window.localStorage.setItem("assistant_ai_notice_ack", "1");
    render(wrap(<AssistantPanel onClose={vi.fn()} />));
    expect(screen.getByText("Hi!")).toBeInTheDocument();
    expect(screen.queryByText("You are chatting with an AI")).not.toBeInTheDocument();
  });

  it("keeps the generated-by hint under the composer before and after the acknowledgement", () => {
    render(wrap(<AssistantPanel onClose={vi.fn()} />));
    const hint = "Answers are generated by Google Gemini and may contain mistakes.";
    expect(screen.getByText(hint)).toBeInTheDocument();
    fireEvent.click(screen.getByRole("button", { name: "Got it" }));
    expect(screen.getByText(hint)).toBeInTheDocument();
  });

  it("keeps Tab inside the dialog while the composer is locked", () => {
    render(wrap(<AssistantPanel onClose={vi.fn()} />));
    const dialog = screen.getByRole("dialog");
    screen.getByRole("button", { name: "Got it" }).focus();
    fireEvent.keyDown(dialog, { key: "Tab" });
    expect(document.activeElement).toBe(screen.getByRole("button", { name: "Close" }));
  });
});
