// @vitest-environment happy-dom
import "@testing-library/jest-dom/vitest";
import { afterEach, describe, expect, it, vi } from "vitest";
import { cleanup, fireEvent, render, screen } from "@testing-library/react";
import { NextIntlClientProvider } from "next-intl";
import { AssistantAiNotice } from "./assistant-ai-notice";

const messages = {
  qa: {
    notice: {
      title: "You are chatting with an AI",
      body: "Answers are generated by Google's Gemini model.",
      acknowledge: "Got it",
    },
  },
};
function wrap(ui: React.ReactNode) {
  return <NextIntlClientProvider locale="en" messages={messages}>{ui}</NextIntlClientProvider>;
}
afterEach(cleanup);

describe("AssistantAiNotice", () => {
  it("tells the reader the answers come from an AI", () => {
    render(wrap(<AssistantAiNotice onAcknowledge={vi.fn()} />));
    expect(screen.getByText("You are chatting with an AI")).toBeInTheDocument();
    expect(screen.getByText("Answers are generated by Google's Gemini model.")).toBeInTheDocument();
  });

  it("calls onAcknowledge when the reader confirms", () => {
    const onAcknowledge = vi.fn();
    render(wrap(<AssistantAiNotice onAcknowledge={onAcknowledge} />));
    fireEvent.click(screen.getByRole("button", { name: "Got it" }));
    expect(onAcknowledge).toHaveBeenCalledOnce();
  });
});
