import { localStorage } from "@/lib/local-storage";

/**
 * AI Act Art. 50(1) (in force since 2026-08-02) and Apple 5.1.2(i): before the
 * first interaction the user is told that the answers are generated by an AI
 * (Google Gemini), may be wrong, and that no other person's personal data
 * belongs in the chat — and acknowledges it explicitly. ADR 0005.
 */
export const AI_NOTICE_KEY = "assistant_ai_notice_ack";

export type AiNoticeState = "pending" | "show" | "hidden";

/** Pure: the screen renders from this and branches nowhere else. */
export function resolveNoticeState({
  loaded,
  acknowledged,
}: {
  loaded: boolean;
  acknowledged: boolean;
}): AiNoticeState {
  if (!loaded) return "pending";
  return acknowledged ? "hidden" : "show";
}

export async function readAiNoticeAcknowledged(): Promise<boolean> {
  try {
    return (await localStorage.getItem(AI_NOTICE_KEY)) === "1";
  } catch {
    return false;
  }
}

export async function acknowledgeAiNotice(): Promise<void> {
  await localStorage.setItem(AI_NOTICE_KEY, "1");
}
