export { ApiClient } from "./client";
export type { AuthStrategy, ApiClientOptions } from "./client";

export { APIError } from "./errors";

export { createApi } from "./create-api";
export type { Api } from "./create-api";

export { buildQueryString } from "./query-string";

export {
  publicEndpoints,
  deviceEndpoints,
  refereeEndpoints,
  refereeAdminEndpoints,
  adminBoardEndpoints,
  matchEndpoints,
  syncEndpoints,
  notificationEndpoints,
  socialEndpoints,
  settingsEndpoints,
  bookingEndpoints,
  teamEndpoints,
  channelConfigEndpoints,
  broadcastEndpoints,
  watchRuleEndpoints,
  eventEndpoints,
  venueEndpoints,
} from "./endpoints";
export type {
  MatchQueryParams,
  PublicTeam,
  RegisterDeviceResponse,
  UnregisterDeviceResponse,
  RefereeGamesQueryParams,
  RefereeListQuery,
  RefereeVisibilityBody,
  UpdateRefereeRulesBodyParsed,
  RefereeHistoryFilterQuery,
  RefereeHistoryGamesQuery,
  TaskCreateBody,
  TaskUpdateBody,
  TaskMoveBody,
  TaskListQuery,
  BoardCreateBody,
  BoardUpdateBody,
  ColumnCreateBody,
  ColumnUpdateBody,
  MatchListQuery,
  MatchUpdateBody,
  MatchHistoryQuery,
  SyncLogsQuery,
  SyncEntriesQuery,
  SyncUpdateScheduleBody,
  NotificationListQuery,
  NotificationPreferencesBody,
  SocialMatchesQuery,
  SocialGenerateBody,
  SettingsClubConfig,
  SettingsBookingConfig,
  SettingsRefereeReminder,
  LeagueNumbersBody,
  LeagueOwnClubRefsBody,
  BookingListQuery,
  BookingCreateBody,
  BookingUpdateBody,
  BookingStatusBody,
  TeamUpdateBody,
  TeamReorderBody,
  ChannelConfigListQuery,
  ChannelConfigCreateBody,
  ChannelConfigUpdateBody,
  BroadcastUpsertBody,
  BroadcastStartStopBody,
  BroadcastMatchesQuery,
  WatchRuleListQuery,
  WatchRuleCreateBody,
  WatchRuleUpdateBody,
  EventListQuery,
  TriggerEventBody,
  VenueSearchQuery,
} from "./endpoints";
