export const SWR_KEYS = {
  syncStatus: "/admin/sync/status",
  syncLogs: (limit: number, offset: number) =>
    `/admin/sync/logs?limit=${limit}&offset=${offset}`,
  syncSchedule: "/admin/sync/schedule",
  matches: "/admin/matches",
  matchDetail: (id: number) => `/admin/matches/${id}`,
  teams: "/admin/teams",
  referees: "/admin/referees",
  standings: "/admin/standings",
  venues: "/admin/venues",
  settingsClub: "/admin/settings/club",
  settingsLeagues: "/admin/settings/leagues",
  users: "admin-users",
  boards: "/admin/boards",
  boardDetail: (id: number) => `/admin/boards/${id}`,
  boardTasks: (boardId: number) => `/admin/boards/${boardId}/tasks`,
  bookings: "/admin/bookings",
  bookingDetail: (id: number) => `/admin/bookings/${id}`,
  settingsBooking: "/admin/settings/booking",
  notificationsUnread: "/admin/notifications/unread-count",
  refereeMatches: "/referee/matches?limit=500&offset=0",
} as const;
